obj-m += hello.o

hello-objs := \
	hello_entry.o \
	wxshadow_compat.o \
	wxshadow_core.o \
	wxshadow_scan.o \
	wxshadow_pgtable.o \
	wxshadow_handlers.o \
	wxshadow_bp.o

ccflags-y += -Wno-unused-parameter -Wno-unused-function -Wno-unused-variable
